### PR TITLE
Use jellyfish-provisioner gem

### PR DESCRIPTION
**Pull request by calebhearth**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@calebthompson  A bit out of the loop on this, but where does "jellyfish-provisioner" come from?

**Comment by calebhearth** [comment]
I pulled it out of jellyfish/api yesterday. You were in a meeting or something at the time so it lives on my github account. If you temporarily make me an admin I can transfer it to the projectjellyfish org.

**Comment by chriskacerguis** [comment]
@calebthompson you're an admin now

**Comment by calebhearth** [comment]
Done. https://github.com/projectjellyfish/jellyfish-provisioner

**Comment by calebhearth** [comment]
This can't happen, though, until #17 is resolved.

**Pull request closed without merging**
